site_name: C&I Team Dashboard
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/logo.png
nav:
  - Home: index.md
  - Team:
    - Technology Products:
      - Overview: team/details.md
      - Important Links: team/links.md
      - Tickets: team/tickets.md
      - Leave Tracker: team/leave-tracker.md
      - Updates: team/updates.md
    - Italy Infra: team/italy-infra.md
    - Network: team/network.md
  - Documents: documents.md
  - Org Chart: orgchart.md
  - Newsletter: newsletter.md

extra_css:
  - assets/css/custom-theme.css
  - assets/css/timeline.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js    # External library via CDN
  - assets/js/dashboard.js                  # Your custom JavaScript file
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search
  - mermaid2

# markdown_extensions:
#   - admonition           # callouts
#   - pymdownx.details     # makes callouts collapsible (???)
#   - pymdownx.superfences # allows rich content inside callouts
#   - def_list             # (optional) nice team: members formatting

markdown_extensions:
  - admonition           # callouts
  - pymdownx.details     # makes callouts collapsible (???)
  - pymdownx.superfences # allows rich content inside callouts
  - def_list             # (optional) nice team: members formatting
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list


repo_url: https://github.com/skyrampravin/team-dashboard
# ...existing code...